networks:
  openteams-network:
    driver: bridge

volumes:
  nextcloud_data:
  nextcloud_db_data:
  nextcloud_redis_data:

services:
  nextcloud_db:
    image: mariadb:10.6
    container_name: openteams-nextcloud-db
    restart: always
    ports:
      - 3306:3306
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - TZ=Asia/Almaty
    volumes:
      - nextcloud_db_data:/var/lib/mysql
    networks:
      - openteams-network

  nextcloud_redis:
    image: redis:6.2-alpine
    container_name: openteams-nextcloud-redis
    restart: always
    command: redis-server --requirepass ${REDIS_PASSWORD}
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - TZ-Asia/Almaty
    volumes:
      - nextcloud_redis_data:/data
    networks:
      - openteams-network

  nextcloud:
    image: nextcloud:latest
    container_name: openteams-nextcloud
    restart: always
    expose:
      - "80"
    environment:
      - REDIS_HOST=nextcloud_redis
      - REDIS_HOST_PASSWORD=${REDIS_PASSWORD}
      - MYSQL_HOST=nextcloud_db
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - TZ=Asia/Almaty
    volumes:
      - nextcloud_data:/var/www/html
    depends_on:
      - nextcloud_db
      - nextcloud_redis
    networks:
      - openteams-network