networks:
  openteams-network:
    driver: bridge

volumes:
  npm_data:


services:
  # Nginx Proxy Manager
  npm:
    container_name: openteams-npm
    image: jc21/nginx-proxy-manager:latest
    restart: always
    ports:
      - "80:80"
      - "81:81"
      - "443:443"
    volumes:
      - npm_data:/data
      - npm_data:/etc/letsencrypt
    environment:
      TZ: Asia/Almaty
    networks:
      - openteams-network