networks:
  openteams-network:
    driver: bridge

volumes:
  mongodb_data:
  wekan_files:

services:
  wekan:
    container_name: openteams-wekan
    image: ghcr.io/wekan/wekan:latest
    restart: always
    ports:
      - 3001:8080
    environment:
      - MONGO_URL=mongodb://mongodb:27017/wekan?replicaSet=rs0
      - ROOT_URL=${WEKAN_ROOT_URL}
      - MAIL_URL
      - MAIL_FROM
      - WITH_API=true
      - DEFAULT_AUTHENTICATION_METHOD=${WEKAN_DEFAULT_AUTHENTICATION_METHOD}
      - LDAP_ENABLE=${WEKAN_LDAP_ENABLE}
      - LDAP_PORT=${WEKAN_LDAP_PORT}
      - LDAP_HOST=${WEKAN_LDAP_HOST}
      - LDAP_BASEDN=${LDAP_BASEDN}
      - LDAP_LOGIN_FALLBACK=false
      - LDAP_RECONNECT=true
      - LDAP_TIMEOUT=10000
      - LDAP_IDLE_TIMEOUT=10000
      - LDAP_CONNECT_TIMEOUT=10000
      - LDAP_AUTHENTIFICATION=${WEKAN_LDAP_AUTHENTIFICATION}
      - LDAP_AUTHENTIFICATION_USERDN=${LDAP_ADMIN_DN}
      - LDAP_AUTHENTIFICATION_PASSWORD=${LDAP_ADMIN_PASSWORD}
      - LDAP_LOG_ENABLED=true
      - LDAP_USER_SEARCH_SCOPE=sub
      - LDAP_USER_SEARCH_FIELD=uid
      - LDAP_UNIQUE_IDENTIFIER_FIELD=uid
      - LDAP_USERNAME_FIELD=uid
      - LDAP_FULLNAME_FIELD=cn
      - LDAP_EMAIL_FIELD=mail
      - LDAP_SYNC_USER_DATA=true
      - LDAP_SYNC_USER_DATA_FIELDMAP={"cn":"name", "mail":"email"}
    depends_on:
      mongodb:
        condition: service_healthy
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - wekan_files:/data:rw
    networks:
      - openteams-network

  mongodb:
    container_name: openteams-mongodb
    image: docker.io/bitnami/mongodb:6.0
    restart: always
    volumes:
      - mongodb_data:/bitnami/mongodb
    environment:
      MONGODB_REPLICA_SET_MODE: "primary"
      MONGODB_REPLICA_SET_NAME: "rs0"
      MONGODB_PORT_NUMBER: "27017"
      MONGODB_INITIAL_PRIMARY_HOST: "mongodb"
      MONGODB_INITIAL_PRIMARY_PORT_NUMBER: "27017"
      MONGODB_ADVERTISED_HOSTNAME: "mongodb"
      MONGODB_ENABLE_JOURNAL: "true"
      ALLOW_EMPTY_PASSWORD: "yes"
    networks:
      - openteams-network
    healthcheck:
      test: ["CMD", "true"]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 30s