networks:
    openteams-network:
        driver: bridge

services:
  focalboard:
    image: mattermost/focalboard:latest
    container_name: openteams-focalboard
    # Internal port only - Nginx Proxy Manager will handle external access
    expose:
      - "8000"
    volumes:
      - ./data:/data
      - ./config:/opt/focalboard/config
    environment:
      # Use your domain name
      - VIRTUAL_HOST=kanban.openteams.me
      - VIRTUAL_PORT=8000
      # Network settings for your environment
      - POSTGRES_DBNAME=focalboard
      - POSTGRES_USER=focalboarduser
      - POSTGRES_PASSWORD=strongpassword
      # Add to your existing network
    networks:
      - openteams-network
    restart: unless-stopped