networks:
    openteams-network:
        driver: bridge

volumes:
  pg_data:

services:
  focalboard:
    image: mattermost/focalboard:latest
    restart: unless-stopped
    container_name: openteams-focalboard
    # Internal port only - Nginx Proxy Manager will handle external access
    expose:
      - "8000"
    volumes:
      - ./data:/data
      - ./config:/opt/focalboard/config
    environment:
      # Use your domain name
      - VIRTUAL_HOST=kanban.openteams.me
      - VIRTUAL_PORT=8000
      # Network settings for your environment
      - POSTGRES_DBNAME=focalboard
      - POSTGRES_USER=focalboarduser
      - POSTGRES_PASSWORD=strongpassword
      # Add to your existing network
    networks:
      - openteams-network

  postgres:
    image: postgres:latest
    container_name: openteams-postgres
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data/pgdata
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M
    command: >
      postgres -c max_connections=1000
               -c shared_buffers=256MB
               -c effective_cache_size=768MB
               -c maintenance_work_mem=64MB
               -c checkpoint_completion_target=0.7
               -c wal_buffers=16MB
               -c default_statistics_target=100

    restart: unless-stopped
    tty: true
    stdin_open: true
    networks:
      - openteams-network