networks:
    openteams-network:
        driver: bridge

services:
  homepage:
    build:
      context: homepage
      dockerfile: homepage/Dockerfile
    container_name: openteams-homepage
    restart: ${RESTART_POLICY:-unless-stopped}
    networks:
      - openteams-network
    volumes:
      - ./homepage:/usr/share/nginx/html
