networks:
  openteams-network:
    driver: bridge

volumes:
  mongodb_data:

services:  
  mongodb:
    container_name: openteams-mongodb
    image: docker.io/bitnami/mongodb:6.0
    restart: ${RESTART_POLICY:-unless-stopped}
    volumes:
      - mongodb_data:/bitnami/mongodb
    environment:
      MONGODB_REPLICA_SET_MODE: "primary"
      MONGODB_REPLICA_SET_NAME: "rs0"
      MONGODB_PORT_NUMBER: "27017"
      MONGODB_INITIAL_PRIMARY_HOST: "mongodb"
      MONGODB_INITIAL_PRIMARY_PORT_NUMBER: "27017"
      MONGODB_ADVERTISED_HOSTNAME: "mongodb"
      MONGODB_ENABLE_JOURNAL: "true"
      ALLOW_EMPTY_PASSWORD: "yes"
    networks:
      - openteams-network
    healthcheck:
      test: ["CMD", "true"]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 30s