networks:
  openteams-network:
    driver: bridge

volumes:
  ldap_data:
  ldap_config:
  ldap_certs:

services:
  openldap:
    image: osixia/openldap:1.3.0
    restart: ${RESTART_POLICY:-unless-stopped}
    container_name: openteams-ldap
    environment:
      LDAP_LOG_LEVEL: "256"
      LDAP_ORGANISATION: ${LDAP_ORGANISATION}
      LDAP_DOMAIN: ${LDAP_DOMAIN}
      LDAP_ADMIN_PASSWORD: ${LDAP_ADMIN_PASSWORD}
    volumes:
      - ldap_data:/var/lib/ldap
      - ldap_config:/etc/ldap/slapd.d
      - ldap_certs:/container/service/slapd/assets/certs
    ports:
      - "389:389"
    networks:
      - openteams-network